### ISSUE TITLE
"pp" clashes with PAR-Packer's "pp"

### ISSUE THREAD

**Issue by eserte** [frioux/app-adenosine#8]
There's already a "pp" script in the CPAN: in the quite popular CPAN distribution PAR-Packer (see https://metacpan.org/release/PAR-Packer ). It would be good if you would rename your "pp" script — currently one cannot install both distributions in the same perl.

**Comment by frioux** [comment]
Ah good call.

-- 
sent from a rotary phone, pardon my brevity

**Comment by frioux** [comment]
Fixed by dropping pp.
